import { Comfortaa } from "next/font/google"

import "./globals.css"

import { Navbar } from "./_components/navbar"

const font = Comfortaa({ subsets: ["cyrillic", "latin"], weight: ["400"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Navbar />
        <main className={"h-full w-full"}>{children}</main>
      </body>
    </html>
  )
}
