import { Comfortaa } from "next/font/google"

import "./globals.css"

import { Navbar } from "./_components/navbar"
import { Footer } from "./_components/footer/ui/footer"
import { ToTopButton } from "./_components/to-top-button/ui/to-top-button"

const font = Comfortaa({ subsets: ["cyrillic", "latin"], weight: ["400"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Navbar />
        <main>{children}</main>
        <ToTopButton className={'fixed bottom-10 right-10 w-[50px] h-[50px] text-[#ada295] cursor-pointer'} />
        <Footer />
      </body>
    </html>
  )
}


